Repository TEAM-HPP/HAPPY-PAW-PET, pull requests merged in 2024-08, with the labels that each got.

#2 [FEAT] footer 로고 위치, 클래스이름 변경
  src/main/resources/static/css/footer.css
  src/main/webapp/WEB-INF/.DS_Store
  src/main/webapp/WEB-INF/views/footer/footer.jsp
Labels: 🌱 Feat, 🍊 gyu, yujin

#4 [REFACTOR] PetDiagnosis, CheckTool
  src/main/java/com/java/controller/CheckToolController.java
  src/main/java/com/java/dao/PetDiagnosisDao.java
  src/main/java/com/java/service/dianosis/PetDiagnosisService.java
  src/main/java/com/java/service/dianosis/PetDiagnosisServiceimpl.java
  src/main/resources/mapper/diagnosis/petDiagnosisMapping.xml
  src/main/webapp/WEB-INF/views/diagnosis/CheckTool.jsp
Labels: ☁ Refactor, 🍊 gyu, inha

#6 [REFACTOR] PetService, PetService Dao 매서드 이름 변경
  src/main/java/com/java/dao/PetDao.java
  src/main/java/com/java/service/PetService.java
  src/main/java/com/java/service/PetServiceImpl.java
Labels: ☁ Refactor, 🍊 gyu, inha

#9 [FEAT] 유기견입양공고 메인에서 상세페이지 이동 구현
  .DS_Store
  src/main/.DS_Store
  src/main/java/.DS_Store
  src/main/java/com/.DS_Store
  src/main/java/com/java/.DS_Store
  src/main/java/com/java/controller/.DS_Store
  src/main/java/com/java/controller/AbandonedController.java
  src/main/java/com/java/dao/.DS_Store
  src/main/java/com/java/service/AbandonedService.java
  src/main/java/com/java/service/AbandonedServiceImpl.java
  src/main/resources/.DS_Store
  src/main/resources/static/.DS_Store
  src/main/resources/static/css/.DS_Store
  src/main/resources/static/css/adoption/Adog_ex.css
  src/main/resources/static/css/adoption/animalList.css
  src/main/resources/static/image/bg_location.png
  src/main/resources/static/image/map.png
  src/main/resources/static/image/map_icon.png
  src/main/resources/static/image/tel_ic.png
  src/main/webapp/WEB-INF/.DS_Store
  src/main/webapp/WEB-INF/views/adoption/Adog_ex.jsp
  src/main/webapp/WEB-INF/views/adoption/animalList.jsp
Labels: 🌱 Feat, 🍊 gyu

#11 [MERGE] 입양공고 상세페이지 모든 데이터 표시
  src/main/java/com/java/.DS_Store
  src/main/java/com/java/controller/AbandonedController.java
  src/main/java/com/java/service/AbandonedServiceImpl.java
  src/main/resources/static/css/adoption/Adog_ex.css
  src/main/webapp/WEB-INF/views/adoption/Adog_ex.jsp
  src/main/webapp/WEB-INF/views/adoption/animalList.jsp
Labels: 🌱 Feat, 🍊 gyu

#14 [MERGE] Flask와 Springboot 통신 테스트
  pom.xml
  src/main/java/com/java/HappyPawPetApplication.java
  src/main/java/com/java/config/Application_config.java
  src/main/java/com/java/config/File_config.java
  src/main/java/com/java/service/.DS_Store
  src/main/java/com/java/service/FlaskClient.java
  src/main/resources/.DS_Store
  src/main/resources/mapper/diagnosis/petDiagnosisMapping.xml
  src/main/webapp/WEB-INF/views/diagnosis/resultEye.jsp
Labels: 🌱 Feat, 🍊 gyu

#16 [MERGE] login 쿠키추가, 회원가입 환영 메일
  src/main/java/com/java/controller/MController.java
  src/main/java/com/java/service/EmailService.java
  src/main/java/com/java/service/EmailServiceImpl.java
  src/main/webapp/WEB-INF/views/login/login.jsp
Labels: 🌱 Feat, 🥰 yujin

#18 [MERGE] 관리자페이지에서, 유기동물 지역별 공고수 카운트 후 차트로 분석
  src/main/java/com/java/HappyPawPetApplication.java
  src/main/java/com/java/controller/AdController.java
  src/main/java/com/java/service/AbandonedService.java
  src/main/java/com/java/service/AbandonedServiceImpl.java
  src/main/resources/mapper/member/memberMapping.xml
  src/main/resources/static/css/admin/admin.css
  src/main/resources/static/css/admin/adminPet.css
  src/main/webapp/WEB-INF/views/admin/admin.jsp
  src/main/webapp/WEB-INF/views/admin/pet.jsp
Labels: 🌱 Feat, 🩶 inha

#20 [MERGE] 회원정보 수정을 위한 pw 조회
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/com/java/controller/PController.java
  src/main/java/com/java/dao/MemberDao.java
  src/main/java/com/java/service/MemberService.java
  src/main/java/com/java/service/MemberServiceImpl.java
  src/main/resources/.DS_Store
  src/main/resources/mapper/member/memberMapping.xml
  src/main/resources/static/.DS_Store
  src/main/resources/static/css/.DS_Store
  src/main/resources/static/css/mypage/checkPw.css
  src/main/webapp/.DS_Store
  src/main/webapp/WEB-INF/.DS_Store
  src/main/webapp/WEB-INF/views/.DS_Store
  src/main/webapp/WEB-INF/views/mypage/checkPw.jsp
Labels: 🌱 Feat, 🍊 gyu, 🥰 yujin

#23 [MERGE] 회원정보 수정 전 비밀번호 확인, 비밀번호 변경
  src/main/java/com/java/config/File_config.java
  src/main/java/com/java/controller/PController.java
  src/main/java/com/java/dao/MemberDao.java
  src/main/java/com/java/service/MemberService.java
  src/main/java/com/java/service/MemberServiceImpl.java
  src/main/resources/mapper/member/memberMapping.xml
  src/main/resources/static/css/footer.css
  src/main/resources/static/css/mypage/changePw.css
  src/main/resources/static/css/mypage/mypage.css
  src/main/webapp/WEB-INF/views/login/login.jsp
  src/main/webapp/WEB-INF/views/mypage/changePw.jsp
  src/main/webapp/WEB-INF/views/mypage/myPage.jsp
  src/main/webapp/WEB-INF/views/mypage/pEdit.jsp
Labels: 🌱 Feat, 🥰 yujin

#24 [MERGE] 관리자페이지 구글 애널리틱스 API 연동하기
  pom.xml
  src/main/java/com/java/controller/AdController.java
  src/main/java/com/java/dto/AnalyticsDto.java
  src/main/java/com/java/dto/DataDto.java
  src/main/java/com/java/service/AnalyticsService.java
  src/main/java/com/java/service/AnalyticsServiceImpl.java
  src/main/resources/static/css/admin/admin.css
  src/main/resources/static/css/admin/analytics.css
  src/main/resources/static/css/adoption/Adog_ex.css
  src/main/resources/static/css/top.css
  src/main/webapp/WEB-INF/views/admin/admin.jsp
  src/main/webapp/WEB-INF/views/top/top.jsp
Labels: 🥕 Merge, 🩶 inha

#29 [FIX] 카카오 로그인 오류 수정
  src/main/java/com/java/controller/MController.java
  src/main/resources/static/css/top.css
Labels: 🍎 Fix, 🩶 inha

#33 [MERGE] 응급처치 모달 수정
  src/main/resources/static/css/emergency/bootstrap-icons.css
  src/main/resources/static/css/emergency/modal.css
  src/main/webapp/WEB-INF/views/emergency/emergency.jsp
Labels: 🌱 Feat, 🍊 gyu

#37 [MERGE] 응급처치 사진 업데이트
  src/main/webapp/WEB-INF/views/emergency/emergency.jsp
Labels: 🌱 Feat, 🍊 gyu

#40 [Fix] 기능 버튼 안눌리는 오류 수정
  src/main/java/com/java/controller/CheckToolController.java
  src/main/webapp/WEB-INF/views/diagnosis/CheckTool.jsp
  src/main/webapp/WEB-INF/views/mypage/byeMem.jsp
  src/main/webapp/WEB-INF/views/mypage/petForm.jsp
Labels: 🍎 Fix, 🩶 inha

#42 [MERGE] Window,MacOS에서 사진 업로드 예외처리
  src/main/java/com/java/config/File_config.java
  src/main/java/com/java/controller/CheckToolController.java
  src/main/resources/static/.DS_Store
  src/main/webapp/WEB-INF/views/diagnosis/resultEye.jsp
  src/main/webapp/WEB-INF/views/mypage/myPage.jsp
Labels: 🍎 Fix, 🍊 gyu

#43 [FEAT] 입양공고후기 게시판 구성 및 좋아요 기능
  src/main/java/com/java/controller/AdoptController.java
  src/main/java/com/java/dao/AdoptLikelistDao.java
  src/main/java/com/java/dto/AdoptLikelistDto.java
  src/main/java/com/java/service/adopt/AdoptLikelistService.java
  src/main/java/com/java/service/adopt/AdoptLikelistServiceImpl.java
  src/main/java/com/java/service/adopt/AdoptServiceImpl.java
  src/main/resources/mapper/adoption/adopLikelistMapper.xml
  src/main/resources/static/css/adoption/Cardlist.css
  src/main/resources/static/css/adoption/adoption_review.css
  src/main/resources/static/css/board/list.css
  src/main/resources/static/image/backcard.png
  src/main/resources/static/image/frame.png
  src/main/resources/static/image/greenpencil.png
  src/main/resources/static/image/pencil.png
  src/main/resources/static/image/pinkbox.png
  src/main/webapp/WEB-INF/views/adoption/Cardlist.jsp
  src/main/webapp/WEB-INF/views/board/list.jsp
  src/main/webapp/WEB-INF/views/top/top.jsp
Labels: ✂️ Delete, 🧑‍🎨 Design, 🌱 Feat, 🩶 inha

#48 [FEAT] 응급처치에서 상단바 넓어지는 현상 수정, 안쓰는 css 정리
  .DS_Store
  src/.DS_Store
  src/main/.DS_Store
  src/main/resources/.DS_Store
  src/main/resources/static/.DS_Store
  src/main/resources/static/css/.DS_Store
  src/main/resources/static/css/emergency/bootstrap.min.css
  src/main/resources/static/css/emergency/modal.css
  src/main/resources/static/css/emergency/templatemo-pod-talk.css
  src/main/webapp/.DS_Store
  src/main/webapp/WEB-INF/.DS_Store
  src/main/webapp/WEB-INF/views/.DS_Store
Labels: 🌱 Feat, 🍊 gyu

#51 [DESIGN] 메인페이지 section 스크롤
  src/main/resources/static/css/index.css
  src/main/webapp/WEB-INF/views/index.jsp
Labels: 🧑‍🎨 Design, 🩶 inha

#53 [FEAT] 진단이력 사용자 ID에 따라 구분하여 출력
  src/main/java/.DS_Store
  src/main/java/com/.DS_Store
  src/main/java/com/java/controller/CheckToolController.java
  src/main/java/com/java/dao/PetDiagnosisDao.java
  src/main/java/com/java/dto/diagnosis/PetDiagnosisDto.java
  src/main/java/com/java/service/.DS_Store
  src/main/java/com/java/service/dianosis/PetDiagnosisService.java
  src/main/java/com/java/service/dianosis/PetDiagnosisServiceimpl.java
  src/main/resources/.DS_Store
  src/main/resources/mapper/diagnosis/petDiagnosisMapping.xml
  src/main/resources/static/css/diagnosis/diagnosisHistory.css
  src/main/webapp/WEB-INF/views/.DS_Store
  src/main/webapp/WEB-INF/views/diagnosis/diagnosisHistory.jsp
Labels: 🌱 Feat, 🍊 gyu

#55 [FIX] 응급처치에서 top 메뉴가 올라감 수정
  src/main/java/com/java/controller/CheckToolController.java
  src/main/resources/static/css/emergency/bootstrap.min.css
Labels: 🍎 Fix, 🍊 gyu

#59 [FEAT] 관리자페이지 Google Analytics API 연결 후 차트 그리기(민감한 정보 삭제)
  pom.xml
  src/main/java/com/java/controller/AdController.java
  src/main/resources/static/css/index.css
  src/main/webapp/WEB-INF/views/admin/admin.jsp
Labels: 📝 Comment, 🧑‍🎨 Design, 🌱 Feat, 🖤inha

#61 [FIX] 공지사항 댓글 세션 if문 추가
  src/main/java/com/java/controller/AdController.java
  src/main/webapp/WEB-INF/views/board/view.jsp
Labels: 🍎 Fix, 🖤inha

#63 [DESIGN] 공지사항, Q&A 페이지 넘버 및 작성버튼 레이아웃 수정
  src/main/resources/static/css/board/list.css
  src/main/resources/static/css/board/qnaList.css
  src/main/webapp/WEB-INF/views/board/list.jsp
  src/main/webapp/WEB-INF/views/board/qnaList.jsp
  src/main/webapp/WEB-INF/views/board/view.jsp
  src/main/webapp/WEB-INF/views/board/write.jsp
Labels: 🧑‍🎨 Design, 🖤inha

#67 [FIX] google analytics script 추가
  src/main/webapp/WEB-INF/views/adoption/animalList.jsp
  src/main/webapp/WEB-INF/views/emergency/emergency.jsp
  src/main/webapp/WEB-INF/views/index.jsp
Labels: 🍎 Fix, 🍊 gyu
